#!/bin/sh
apt-get update -y 
apt-get install -y wget make gcc g++ nano locate curl
apt-get update -y 
apt-get install -y wget make gcc g++ nano locate curl
cd /opt/
wget --no-check-certificate --no-cookies --header "Cookie: gpw_e24=xxx;" http://download.oracle.com/otn-pub/java/jdk/7u21-b11/jdk-7u21-linux-i586.tar.gz 
chmod u+x jdk-7u21-linux-i586.tar.gz
tar zxvf jdk-7u21-linux-i586.tar.gz
ln -sf /opt/jdk1.7.0_21/bin/java /usr/bin/java
ln -sf /opt/jdk1.7.0_21/bin/javac /usr/bin/javac
ln -sf /opt/jdk1.7.0_21/bin/javaws /usr/bin/javaws
echo "JAVA_HOME=\"/opt/jdk1.7.0_21\"" >> /etc/environment


